alias reg-modem='atc at+cops?'
alias init-modem='atc at+cpin? && atc at+cimi && atc at+cops? && modem-cmd /dev/ttyACM1 at^smoni 2 && modem-cmd /dev/ttyACM1 at^swwan=1,1 3'
alias usb0ip='ip a sh dev usb0'
alias modemip='atc at+cgpaddr'
alias showip='usb0ip && modemip && ip r'
alias ap-state='watch -n 10 -dc sudo systemctl status hostapd' 
alias ap-stop='sudo systemctl stop hostapd' 
alias ap-start='sudo systemctl start hostapd' 
alias ap-enable='sudo systemctl enable hostapd' 
alias ap-disable='sudo systemctl disable hostapd' 
alias wwanman-state='watch -n 10 -dc sudo systemctl status plas9-wwan-manager.service'
alias wwanman-stop='sudo systemctl stop plas9-wwan-manager'
alias wwanman-start='sudo systemctl start plas9-wwan-manager'
alias slog='tail -f /var/log/syslog'
alias reset-modem='sudo plas9-reset && sudo systemctl restart plas9-wwan-manager &&  watch -n 10 -dc sudo systemctl status plas9-wwan-manager.service'
